version: '3.1'
services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=pix
      - POSTGRES_USER=pix
      - POSTGRES_PASSWORD=12345678
      - MAX_CONNECTIONS=300